// Rewrites README.md so alt texts stay in sync with the latest stats.
// The console is one <p> of <img> slices. No whitespace between sibling images.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const readJson = async (f) => JSON.parse(await readFile(path.join(ROOT, "data", f), "utf8"));

const stats = await readJson("stats.json");
const { projects } = await readJson("projects.json");
const user = stats.user;

const img = (src, width, alt) =>
  `<img src="${src}" width="${width}" align="top" alt="${alt.replace(/"/g, "&quot;")}">`;

const cards = projects
  .map((p) => `<a href="${p.href}">${img(`./assets/projects/${p.repo}.svg`, "50%", `${p.repo}: ${p.lines.join(" ")}`)}</a>`)
  .join("");

const md = `<!--
  CYBERPUNK CONSOLE PROFILE
  Slices are generated by scripts/ and refreshed by .github/workflows/update-profile.yml.
  Edit data/projects.json or scripts/lib/*.mjs — not assets/.
  Keep images on one line with no whitespace between them, or the console splits.
-->
<p align="center">
${img("./assets/00-header.svg", "100%", `배근태 - Backend Developer, Night City console`)}
${img("./assets/01-identity.svg", "100%", `${user} is a backend developer working with Java Spring boot, Node.js, JavaScript, TypeScript, NestJS, interested in AI-assisted development and automation`)}
${img("./assets/02-city.svg", "100%", `Contribution City: every day of the last year is a building. Taller means more contributions. Peak ${stats.busiest?.count ?? 0} on ${stats.busiest?.date ?? "n/a"}`)}
${img("./assets/03-status.svg", "100%", `Status: ${stats.lastYear} contributions in the last year, current streak ${stats.currentStreak} days, longest streak ${stats.longestStreak} days, ${stats.repos} public repositories`)}
${img("./assets/04-projects-head.svg", "100%", "Projects")}
${cards}<a href="https://github.com/${user}?tab=repositories">${img("./assets/04-projects-more.svg", "100%", `Browse all repositories of ${user}`)}</a>
${img("./assets/05-stack.svg", "100%", "Tech stack: TypeScript, JavaScript, Java, Node.js, NestJS, Express, PostgreSQL, Redis, BullMQ, Kafka, Gemini and OpenAI APIs, GitHub Actions, Docker")}
${img("./assets/06-footer.svg", "100%", `Auto-update pipeline: GitHub Actions cron, fetch, render, commit. Last sync ${stats.lastDataDate}`)}
</p>
`;

await writeFile(path.join(ROOT, "README.md"), md);
console.log("[readme] wrote README.md");
